### ISSUE TITLE
Get Total endpoint not working

### ISSUE THREAD

**Issue by gabeodess** [FloristOne/FloristOne_API#1]
Hello,

I can't seem to get this endpoint to work.  All other endpoints are working which tells me that my authentication is correct.  

Do you see anything wrong with my request?  Please advise!

![screen shot 2016-07-14 at 1 58 57 pm](https://cloud.githubusercontent.com/assets/65213/16850090/7f95a11a-49cb-11e6-81a9-33c6b528a465.png)

**Comment by losrobots** [comment]
Hey Gabe, 

Your arguments look correct but the endpoint is wrong and it is because it was wrong in the docs! It should be https://www.floristone.com/api/rest/flowershop/gettotal . 

Please try adding the /rest/ folder to the endpoint and let me know. 

Thanks for bringing this to our attention.

**Comment by gabeodess** [comment]
Worked like a charm, thanks!
